export const data = [
	{
		id: 1,
		img: "assets/images/1.png",
		name: "Carrot",
		price: "2",
		tag: "Vegetables",
		kg: "1 kilogram",
	},
	{ id: 2, img: "assets/images/2.png", name: "Brocoli", price: "3", tag: "Vegetables", kg: "1 kilogram" },
	{ id: 3, img: "assets/images/3.png", name: "Cucumber", price: "3.5", tag: "Vegetables", kg: "3 kilogram" },
	{ id: 4, img: "assets/images/4.png", name: "Eggplant", price: "4.1", tag: "Vegetables", kg: "2 kilogram" },
	{ id: 5, img: "assets/images/5.png", name: "Dragon Fruit", price: "1.6", tag: "Fruits", kg: "1 kilogram" },
	{ id: 6, img: "assets/images/6.png", name: "Apple", price: "0.9", tag: "Fruits", kg: "0.5 kilogram" },
	{ id: 7, img: "assets/images/7.png", name: "Orange", price: "5", tag: "Fruits", kg: "3 kilogram" },
	{ id: 8, img: "assets/images/8.png", name: "Tomato", price: "4", tag: "Vegetables", kg: "1 kilogram" },
	{ id: 9, img: "assets/images/9.png", name: "Cherry", price: "6", tag: "Fruits", kg: "2 kilogram" },
	{ id: 10, img: "assets/images/10.png", name: "Lettuce", price: "10", tag: "Vegetables", kg: "5 kilogram" },
	{ id: 11, img: "assets/images/11.png", name: "Mustard", price: "7.5", tag: "Vegetables", kg: "2 kilogram" },
	{ id: 12, img: "assets/images/12.png", name: "Grape Fruit", price: "1.8", tag: "Fruits", kg: "1 kilogram" },
	{ id: 13, img: "assets/images/13.png", name: "Kiwi", price: "2.5", tag: "Fruits", kg: "1 kilogram" },
	{ id: 14, img: "assets/images/14.png", name: "Pineapple", price: "1", tag: "Fruits", kg: "1 kilogram" },
	{ id: 15, img: "assets/images/15.png", name: "Strawberry", price: "7.4", tag: "Fruits", kg: "3 kilogram" },
	{ id: 16, img: "assets/images/16.png", name: "Watermelon", price: "3.3", tag: "Fruits", kg: "1 kilogram" },
	{ id: 17, img: "assets/images/17.png", name: "Strawberry Milk", price: "2", tag: "Drinks", kg: "1 glass" },
	{ id: 18, img: "assets/images/18.png", name: "Choco chip", price: "1", tag: "Dessert", kg: "1 piece" },
	{ id: 19, img: "assets/images/19.png", name: "Cupcake", price: "1.3", tag: "Dessert", kg: "1 piece" },
	{ id: 20, img: "assets/images/20.png", name: "Macaron", price: "2.3", tag: "Dessert", kg: "2 kilogram" },
	{ id: 21, img: "assets/images/21.png", name: "Popcorn", price: "6.3", tag: "Snacks", kg: "1 piece" },
	{ id: 22, img: "assets/images/22.png", name: "Popsicle ", price: "3.3", tag: "Dessert", kg: "1 piece" },
	{ id: 23, img: "assets/images/23.png", name: "Bread", price: "3.3", tag: "Breads", kg: "1 loaf" },
	{ id: 24, img: "assets/images/24.png", name: "Frappe", price: "3.3", tag: "Drinks", kg: "1 glass" },
	{ id: 25, img: "assets/images/25.png", name: "Orange Juice", price: "3.3", tag: "Drinks", kg: "1 glass" },
	{ id: 26, img: "assets/images/26.png", name: "Cocktail", price: "3.3", tag: "Drinks", kg: "1 glass" },
	{ id: 27, img: "assets/images/27.png", name: "Coffee Glass", price: "3.3", tag: "Drinks", kg: "1 glass" },
	{ id: 28, img: "assets/images/28.png", name: "Kebab", price: "1", tag: "Meat and fish", kg: "2 piece" },
	{ id: 29, img: "assets/images/29.png", name: "Chicken", price: "3", tag: "Meat and fish", kg: "1 piece" },
	{ id: 30, img: "assets/images/30.png", name: "Pizza", price: "7", tag: "Meat and fish", kg: "3 piece" },
	{ id: 31, img: "assets/images/31.png", name: "Taco", price: "2", tag: "Meat and fish", kg: "1 piece" },
	{ id: 32, img: "assets/images/32.png", name: "Hot dog", price: "3.3", tag: "Meat and fish", kg: "1 piece" },
	{ id: 33, img: "assets/images/33.png", name: "Spaghetti", price: "3.3", tag: "Pasta", kg: "1 piece" },
	{ id: 34, img: "assets/images/34.png", name: "Cake", price: "5.3", tag: "Dessert", kg: "3 piece" },
	{ id: 35, img: "assets/images/35.png", name: "Pancake", price: "1.3", tag: "Dessert", kg: "2 piece" },
	{ id: 36, img: "assets/images/36.png", name: "Ice cream", price: "2.2", tag: "Dessert", kg: "1 kilogram" },
	{ id: 37, img: "assets/images/37.png", name: "Japanese Foods", price: "5.2", tag: "Japanese Foods", kg: "2 piece" },
	{ id: 38, img: "assets/images/38.png", name: "Onigiri", price: "4.13", tag: "Japanese Foods", kg: "1 piece" },
	{ id: 39, img: "assets/images/39.png", name: "Noodles", price: "7.3", tag: "Pasta", kg: "1 piece" },
	{ id: 40, img: "assets/images/40.png", name: "Sushi", price: "3.6", tag: "Japanese Foods", kg: "2 piece" },
	{ id: 41, img: "assets/images/41.png", name: "Breakfast", price: "3.3", tag: "Breakfast", kg: "3 piece" },
	{ id: 42, img: "assets/images/42.png", name: "Sandwich", price: "5.3", tag: "Breakfast", kg: "1 piece" },
	{ id: 43, img: "assets/images/43.png", name: "Waffle", price: "2.3", tag: "Dessert", kg: "2 piece" },
	{ id: 44, img: "assets/images/44.png", name: "Toast", price: "1.4", tag: "Breakfast", kg: "2 piece" },
	{ id: 45, img: "assets/images/45.png", name: "Burger", price: "3.7", tag: "Meat and fish", kg: "1 piece" },
	{ id: 46, img: "assets/images/46.png", name: "French Fries", price: "1.3", tag: "Snacks", kg: "2 piece" },
	{ id: 47, img: "assets/images/47.png", name: "Donut", price: "5.3", tag: "Dessert", kg: "3 piece" },
].sort((a, b) => {
	if (a.name < b.name) {
		return -1;
	}
	if (a.name > b.name) {
		return 1;
	}
	return 0;
});
